name: Generate Papers Table

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  push:
    branches: [ main ]
    paths:
      - 'data/papers.jsonl'

jobs:
  generate-table:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Generate Markdown Table
      run: |
        python scripts/generate_table.py
        
    - name: Commit and Push Changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add PAPERS.md
        git commit -m "Update papers table" || exit 0
        git push origin main 
